name: CI

on: [ push ]

jobs:
  cypress:
    run-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando dependencias
        run: npm i
      - name: Subindo aplicacao
        run: npm run start &
      - name: Rodando testes e2e com Cypress
        run: npm run cypress:run